openapi: 3.0.0
info:
  title: API Reference
  description: The Linkage API is built on RESTful principles and returns JSON encoded-responses and accepts JSON payloads. It is only available through HTTPS to ensure the security of the data in transfer.
  contact:
    name: Linkage
    url: https://linkagehq.com/contact-us
    email: contact@linkagehq.com
  version: v1.0.0
servers:
# Added by API Auto Mocking Plugin
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/LinkageHQ/Api-Documentation/v1.0.0
- url: https://docs.linkagehq.com/api/v1.0/
  description: sandbox server
tags:
- name: User
- name: User tokens
- name: Accounts
- name: Profiles
- name: Reputations
- name: Documents
- name: Vehicles
- name: Payouts
- name: Finances
- name: Activities
- name: Webhooks
paths:
  /users/{id}:
    get:
      tags:
      - User
      summary: Retrieves a user by id.
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: string
  
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetails'
        
  /users:
    get:
      tags:
      - User
      description: verifies a user and gets their details
      operationId: Get User Details
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDetails'
  /accounts:
    get:
      tags:
      - Accounts
      description: verifies a user and gets their details
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountDetails'                  
  /accounts/{id}:
    get:
      tags:
      - Accounts
      summary: Retrieves a user by id.
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: string
  
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDetails'
  
    delete:
      tags:
      - Accounts
      summary: Deletes a user id
      parameters:
        - name: id
          in: path
          description: account id
          required: true
          schema:
            type: string
  
      responses:
        '204':
          description: Successful operation
    
  /user-tokens:
    post:
      tags:
      - User tokens
      description: User tokens are temporary access keys that ensure Argyle Link users permissions are scoped to the specified users data.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: string
              example:   # Sample object
                user: user-id
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  access:
                    type: string
                example:
                  access: user-token
  /profiles:
    get:
      tags:
      - Profiles
      description: verifies a user and gets their details
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProfileDetails'                  
  /profiles/{id}:
    get:
      tags:
      - Profiles
      summary: Retrieves a user by id.
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: string
  
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileDetails'
  
  /reputations:
    get:
      tags:
      - Reputations
      description: verifies a user and gets their details
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReputationDetails'                  
  /reputations/{id}:
    get:
      tags:
      - Reputations
      summary: Retrieves a user by id.
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: string
  
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReputationDetails'
               
components:
  schemas:
    UserDetails:
      type: object
      properties:
        id:
          type: string
          example: '0994b847-cc69-4d98-bc99-c5e65e762add'
        created_at:
          type: string
          example: '2019-11-27T15:56:50.583233Z'
        data_providers_connected:
          type: array
          items:
            type: string
      description: 'User objects represent distinct users that used linkagehq plugin to connect their workforce accounts.'
      
    AccountDetails:
      type: object
      properties:
        id:
          type: string
          example: 'ac81e2bc-2157-4535-8ca4-fb1f068df1fc'
        user:
          type: string
          example: 'ac81e2bc-2157-4535-8ca4-fb1f068df1fc'
        created_at:
          type: string
          example: '2019-11-27T15:56:50.583233Z'
        updated_at:
          type: string
          example: '2019-11-27T15:56:50.583233Z'
        connection:
          type: object
          properties:
            status:
              type: string
              example: connected
            error_code:
              type: string
              example: null
            updated_at:
              type: string
              example: 2019-11-29T08:37:42.112859  
        availability:
          type: object
          properties:
            vehicles:
              type: object
              properties:
                status:
                  type: string
                  example: synced
                updated_at:
                  type: string
                  example: 2019-11-27T15:56:20.699808
            documents:
              type: object
              properties:
                status:
                  type: string
                  example: synced
            profiles:
              type: object
              properties:
                status:
                  type: string
                  example: synced
                updated_at:
                  type: string
                  example: 2019-11-27T15:56:20.699808
            reputations:
              type: object
              properties:
                status:
                  type: string
                  example: synced
                updated_at:
                  type: string
                  example: 2019-11-27T15:56:20.699808
        data_partner:
          type: string
          example: greyhr
            
    ProfileDetails:
      type: object
      properties:
        id:
          type: string
          example: '47b216e2-d334-4235-bc1e-185d15ab18d0'
        account:
          type: string
          example: '010db8b4-a724-47fc-a17e-733b656312a2'
        created_at:
          type: string
          example: '2019-11-27T15:56:50.583233Z'
        updated_at:
          type: string
          example: '2019-11-27T15:56:50.583233Z'
        first_name:
          type: string
          example: 'max'
        last_name:
          type: string
          example: 'payne'
        full_name:
          type: string
          example: 'max payne'
        phone_number:
          type: string
          example: '+12 67579 54645' 
        birth_date:
          type: string
          example: '+12 67579 54645'  
        picture_url:
          type: string
          example: '+12 67579 54645'  
        address:
          type: object
          properties:
            city:
              type: string
              example: NEW YORK
            line1:
              type: string
              example: NEW YORK
            line2:
              type: string
              example: NEW YORK
            state:
              type: string
              example: NEW YORK
            country:
              type: string
              example: NEW YORK 
            postal_code:
              type: string
              example: NEW YORK
        employment_status:
          type: string
          example: 'active' 
        employment_type:
          type: string
          example: 'part time'
        job_title:
          type: string
          example: 'Driver' 
        aadhaar_number:
          type: string
          example: '***-***-**15' 
        platform_user_id:
          type: string
          example: 'b18d015a'  
        marital_status:
          type: string
          example: 'married' 
        gender:
          type: string
          example: 'male'  
        hire_dates:
          type: array
          items:
              type: string
              example: '2019-01-15T08:00:22.386555Z'
        terminations:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                example: '2019-06-15T00:00:22.142321Z'
              reason:
                type: string
                example: 'contract ended'

    ReputationDetails:
      type: object
      properties:
        id:
          type: string
          example: '47b216e2-d334-4235-bc1e-185d15ab18d0'
        client:
          type: string
          example: '010db8b4-a724-47fc-a17e-733b656312a2'
        created_by:
          type: string
          example: '82bc04fa-1e11-43f2-9a88-357f865b4998'  
        created_at:
          type: string
          example: '2019-11-27T15:56:50.583233Z'
        updated_at:
          type: string
          example: '2019-11-27T15:56:50.583233Z'
        rating:
          type: string
          example: 4.95
        acceptance_rate:
          type: string
          example: 0.86
        ontime_rate:
          type: string
          example: 0.80
        account:
          type: string
          example: 010db8b4-a724-47fc-a17e-733b656312a2 
        achievements:
          type: array
          items:
            type: object
            properties:
              count:
                type: integer
                example: 1
              label:
                type: string
                example: perfect_rating 
              badge_url:
                type: string
                example: https://media.website.com/1554853.png
              description:
                type: string
                example: 'Earned on total 5-star ratings'
