/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.21).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Body;
import io.swagger.model.InlineResponse200;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-09-26T10:30:08.165Z[GMT]")
@Api(value = "user-tokens", description = "the user-tokens API")
public interface UserTokensApi {

    @ApiOperation(value = "Create a token", nickname = "getUserToken", notes = "To create a user token send a POST request with the request body containing a json object of the following format", response = InlineResponse200.class, tags={ "User tokens", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The user token enclosed in a json object: {\"access\": \"user-token\"}.", response = InlineResponse200.class) })
    @RequestMapping(value = "/user-tokens",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<InlineResponse200> getUserToken(@ApiParam(value = ""  )  @Valid @RequestBody Body body
);

}

